### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by Nikro** [Nikro/ask-and-start#1]
We need to restructure a bit the homepage.

- Remove the image pane;
- Remove the Q&A pane;
- Remove the Tuts & Experience pane;
- Edit search -> Remove these dropdowns (Location / Industry);
- Create the "Latest Updates" pane - a mixed view-pane that shows all the teasers for all CT: questions, tutorials and shared experience;
- Create the "Announcements" pane - a view-pane that shows all the published announcements (title + wysiwyg body + date/time);

For now this is what we know.

**Comment by marjina-constantin** [comment]
All subtasks are done.

**Comment by Nikro** [comment]
Okay, we've discussed with @afinika and we decided to have Latest Updates as Quicktabs (read: just tabs) with the following tabs:
* All - a mixed view that @marjina-constantin created.
* Q&A - all Q&As
* Tuts - all tutorials
* Experience - all experiences

And, because desktop version of the page will have a missing right side, we will added something like "Trending" or "Popular" (we can hide those on mobile version). It's just that we *do* need to fill-up the right side of the homepage with something.

@alawrence7 - do we have any replacement / ideas on how we want to replace the image that Rosaura did?

**Comment by Nikro** [comment]
Okay, re-deployed on the *dev*, looks good. I will only need to do some tab-related style adjustments and make sure it looks good on mobile.

**Comment by alawrence7** [comment]
@Nikro - Can we leave that image for the MVP then we can work on something new for the next version?

**Comment by Nikro** [comment]
So, I've pushed final front-end changes to the _dev_. I didn't put that image though.
Any final thoughts?
