### ISSUE TITLE
Categories Page

### ISSUE THREAD

**Issue by Nikro** [Nikro/ask-and-start#3]
We need to create a page with all of the 'categories'. What are these? They are basically Top-Level Terms from these vocabularies, each lives as a separate 'pane':

- Industries
- Official Parties
- Locations
- Legal Types
- Tags (default)

And probably on top of all of these we will need to have some information pane (custom pane).

**Comment by marjina-constantin** [comment]
Created "Categories" page. Needs styling.

**Comment by Nikro** [comment]
Finished styling.
